<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>AnyCPU;x86</Platforms>
    <ApplicationIcon>PSOBBIO_icon.ico</ApplicationIcon>
    <Version>1.01</Version>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <FileVersion>1.0.1.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="PSOBBIO_icon.ico" />
    <Resource Include="PSOBBIObanner.png" />
  </ItemGroup>

</Project>
